force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>This object stores information about the boookings.</description>
    <label>Booking</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
                <default>true</default>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Over</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateBookingStatusScheduler.cls
global class UpdateBookingStatusScheduler implements Schedulable{
	    global void execute(SchedulableContext sc) {
        
        // Get the current date
		Date currentDate = Date.today();
        // Get the current time
		Time currentTime = Time.newInstance(System.now().hour(), System.now().minute(), System.now().second(), System.now().millisecond());

        
       	// Query for booking records where the date and end time match the current system datetime
		List<Booking__c> bookingsToUpdate = [SELECT Id FROM Booking__c WHERE Date__c = :currentDate AND End_Time__c <= :currentTime];

        // Update the status of matching booking records to "Over"
        List<Booking__c> bookingsToUpdateStatus = new List<Booking__c>();
        for (Booking__c booking : bookingsToUpdate) {
            booking.Status__c = 'Over';
            bookingsToUpdateStatus.add(booking);
        }
        update bookingsToUpdateStatus;
    }
}